"""Add user relationship to Reservation

Revision ID: f0704b043916
Revises: 9d7e6c1cd31b
Create Date: 2024-08-13 16:53:32.207556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0704b043916'
down_revision: Union[str, None] = '9d7e6c1cd31b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            'fk_reservation_user_id_user', 'user', ['user_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_constraint(
            'fk_reservation_user_id_user', type_='foreignkey'
        )
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
